### ISSUE TITLE
Add missing dep "tabulate"

### ISSUE THREAD

**Issue by mrakitin** [nsls-ii-forge/ispyb-feedstock#2]

**Comment by mrakitin** [comment]
@JunAishima, do you know it's missing/needed in the latest conda environments?

**Comment by JunAishima** [comment]
I don't know - will investigate in the next couple of days

**Comment by JunAishima** [comment]
yes, it appears to still be required - https://github.com/DiamondLightSource/ispyb-api/blob/dd56046c38f9a6bacab8fc81800f6ea6c621841d/setup.py#L6
